version: "3.7"

services:
  docs:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
   app:
    image: mycontainer.azurecr.io/myapp
    restart: always
    environment:
      - AZURE_STORAGE_ACCOUNT=${AZURE_STORAGE_ACCOUNT}
      - AZURE_STORAGE_KEY=${AZURE_STORAGE_KEY}
      - AZURE_CONTAINER_NAME=s2blob
      - MOUNT_PATH=/mnt/blob
    volumes:
      - blob-storage:/mnt/blob
    ports:
      - 8000:8000
   volumes:
     blob-storage:
       driver: "local"
       driver_opts:
         type: "none"
         device: "/mnt/blob"
         o: "bind"
