version: "3.7"

services:
  docs:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    app:
    image: basicacr1.azurecr.io/getting-started
    restart: always
    environment:
      - AZURE_STORAGE_ACCOUNT=s2storage
      - AZURE_STORAGE_KEY=CfjTO14+iouFbekebcaTmcarZC1OH1e4nKvVm4ncyMZlKeLxwDstehakMgsO85qRHfV6DjhDp2MD+ASt5W3cJA==
      - AZURE_CONTAINER_NAME=s2blob
      - MOUNT_PATH=/mnt/blob
    volumes:
      - blob-storage:/mnt/blob
    ports:
      - 3000:3000
  volumes:
   blob-storage:
    driver: "local"
    driver_opts:
      type: "none"
      device: "/mnt/blob"
      o: "bind"
